on:
  issues:
    types:
      - opened

jobs:
  bugfixer:
    runs-on: ubuntu-latest
    name: Use AI to fix simple bugs and make a PR
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Bugfixer
        id: bugfixer
        uses: hershaw/bugfixer@v19
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
